[package]
name = "apollo-rust-xacro"
version = "0.1.0"
edition = "2024"

[dependencies]
roxmltree = "0.19"
evalexpr = "11.3"
regex = "1.10"
walkdir = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
apollo-rust-file = { path = "../apollo-rust-file" }
colored = "3.0"
