[package]
name = "apollo-rust-interpolation"
version = "0.1.0"
edition = "2021"

[dependencies]
apollo-rust-linalg = { path = "../apollo-rust-linalg" }
nalgebra = { version = "0.34.1", features = ["rand", "serde-serialize"] }
